Add support for 1.19
PrismarineJS/node-minecraft-protocol pull request #1006
Opened 2022-06-08 22:31 UTC by Moudoux

1.19 introduces additional key exchanging, and the login process has been modified. This PR outlines a rough prototype on how to use the new system. Key verification is not yet implemented, but can easily be extracted from the Minecraft login packet as it contains the code required to verify.

It also appears necessary to change the client version in the handshake due to the new login protocol changes, or else the client won't connect.

2022-06-14 19:25 UTC, andriycraft requested changes

2022-06-14 19:25 UTC, andriycraft commented on src/server/handshake.js
> +    /*
Why this got commented?

2022-06-14 19:25 UTC, andriycraft commented on src/server/handshake.js
> +    */
same here

2022-06-14 19:25 UTC, andriycraft commented on src/version.js
>    defaultVersion: '1.18.2',
mabye change to 1.19?

2022-06-15 20:31 UTC, IceTank commented
CI is failing

2022-06-19 06:16 UTC, SpencerBurgess commented
> CI is failing

I believe the CI is failing due to the code the author commented out. @Moudoux are you still working on this?

I can take a look over the next few days, getting excited to have the library working with 1.19

2022-06-19 14:01 UTC, Moudoux commented
I'm not working on this, I have a working version of the library for personal use, and this PR serves to show the changes needed to be made to the login procedure in order for 1.19 clients to connect. It is not complete (Player key needs to be verified)

2022-07-19 20:40 UTC, closed without merging