Fix issues with servers sending un-escaped newlines
PrismarineJS/node-minecraft-protocol pull request #1008
Opened 2022-06-15 00:57 UTC by rtm516

If a server sent a response like the below it would cause an `Uncaught SyntaxError: Unexpected token x in JSON at position x` error. Escaping the newlines fixes this issue and more accurately follows the vanilla clients parsing of it.
```
{"version": {"name":"§9gameshield.gg", "protocol":-1}, "description":"§7Cannot connect to §951.222.139.92\n§7For more information visit §9gameshield.gg","text":"§9GameShield\n\n§7The server you are trying to connect to is not found, or is not responding.\nPlease try again later.\n\nFor more information visit §9gameshield.gg"}
```

2022-07-19 20:52 UTC, rom1504 commented on src/ping.js
> +      packet.response = packet.response.replace(/\n/g, '\\n')
Can you put it into a function like parseLenientJson ?

Apparently this is not json

2022-08-07 14:44 UTC, rom1504 commented
can you fix lint / ci ?

2022-10-08 21:29 UTC, rtm516 commented
> can you fix lint / ci ?

Doesnt look like there is an issue that was introduced here, have you tried re-triggering it?

2022-11-11 11:38 UTC, rom1504 requested changes
fix ci please

2023-01-15 17:38 UTC, rom1504 commented
doesn't make sense to me

let's instead maybe add a try catch to avoid crashing if the server sends invalid content

2023-01-15 17:38 UTC, closed without merging