Add IPv6 support by default
PrismarineJS/node-minecraft-protocol pull request #759
Opened 2020-08-30 09:28 UTC by Saiv46

2020-08-30 10:03 UTC, rom1504 requested changes
If the purpose of this change is to set host to undefined by default, I'd better you put host = undefined explicitly even if it means the same

2020-08-30 11:36 UTC, rom1504 commented
And can you point to the doc saying that undefined means "listen to all
ipv4 and ipv6 adresses" ? That seems unlikely to me

On Sun, Aug 30, 2020, 11:28 Alexander Ivanov <notifications@github.com>
wrote:

> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/PrismarineJS/node-minecraft-protocol/pull/759
> Commit Summary
>
>    - Add IPv6 support by default
>
> File Changes
>
>    - *M* src/createServer.js
>    <https://github.com/PrismarineJS/node-minecraft-protocol/pull/759/files#diff-72d0c3f9716fb76809b19c5c3290d7c2>
>    (2)
>
> Patch Links:
>
>    -
>    https://github.com/PrismarineJS/node-minecraft-protocol/pull/759.patch
>    - https://github.com/PrismarineJS/node-minecraft-protocol/pull/759.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/PrismarineJS/node-minecraft-protocol/pull/759>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAR437QQRJO64SRPADXA7YTSDILSZANCNFSM4QPQRI5Q>
> .
>

2020-08-30 11:53 UTC, rom1504 commented
Still better to do host = undefined to make it explicit it's optional

On Sun, Aug 30, 2020, 13:48 Romain Beaumont <romain.rom1@gmail.com> wrote:

>
> https://nodejs.org/api/net.html#net_server_listen_port_host_backlog_callback
> indeed seems like you right, undefined means ipv6+ipv4 on all addresses
>
> On Sun, Aug 30, 2020, 13:47 Romain Beaumont <romain.rom1@gmail.com> wrote:
>
>>
>> https://github.com/PrismarineJS/node-minecraft-protocol/blob/8e4978f3793504435d1b8d7235173f2075ce94db/src/server.js#L53
>> host option goes there fyi
>>
>> On Sun, Aug 30, 2020, 13:35 Romain Beaumont <romain.rom1@gmail.com>
>> wrote:
>>
>>> And can you point to the doc saying that undefined means "listen to all
>>> ipv4 and ipv6 adresses" ? That seems unlikely to me
>>>
>>> On Sun, Aug 30, 2020, 11:28 Alexander Ivanov <notifications@github.com>
>>> wrote:
>>>
>>>> ------------------------------
>>>> You can view, comment on, or merge this pull request online at:
>>>>
>>>>   https://github.com/PrismarineJS/node-minecraft-protocol/pull/759
>>>> Commit Summary
>>>>
>>>>    - Add IPv6 support by default
>>>>
>>>> File Changes
>>>>
>>>>    - *M* src/createServer.js
>>>>    <https://github.com/PrismarineJS/node-minecraft-protocol/pull/759/files#diff-72d0c3f9716fb76809b19c5c3290d7c2>
>>>>    (2)
>>>>
>>>> Patch Links:
>>>>
>>>>    -
>>>>    https://github.com/PrismarineJS/node-minecraft-protocol/pull/759.patch
>>>>    -
>>>>    https://github.com/PrismarineJS/node-minecraft-protocol/pull/759.diff
>>>>
>>>> —
>>>> You are receiving this because you are subscribed to this thread.
>>>> Reply to this email directly, view it on GitHub
>>>> <https://github.com/PrismarineJS/node-minecraft-protocol/pull/759>, or
>>>> unsubscribe
>>>> <https://github.com/notifications/unsubscribe-auth/AAR437QQRJO64SRPADXA7YTSDILSZANCNFSM4QPQRI5Q>
>>>> .
>>>>
>>>

2020-08-30 11:53 UTC, rom1504 commented
https://github.com/PrismarineJS/node-minecraft-protocol/blob/8e4978f3793504435d1b8d7235173f2075ce94db/src/server.js#L53
host option goes there fyi

On Sun, Aug 30, 2020, 13:35 Romain Beaumont <romain.rom1@gmail.com> wrote:

> And can you point to the doc saying that undefined means "listen to all
> ipv4 and ipv6 adresses" ? That seems unlikely to me
>
> On Sun, Aug 30, 2020, 11:28 Alexander Ivanov <notifications@github.com>
> wrote:
>
>> ------------------------------
>> You can view, comment on, or merge this pull request online at:
>>
>>   https://github.com/PrismarineJS/node-minecraft-protocol/pull/759
>> Commit Summary
>>
>>    - Add IPv6 support by default
>>
>> File Changes
>>
>>    - *M* src/createServer.js
>>    <https://github.com/PrismarineJS/node-minecraft-protocol/pull/759/files#diff-72d0c3f9716fb76809b19c5c3290d7c2>
>>    (2)
>>
>> Patch Links:
>>
>>    -
>>    https://github.com/PrismarineJS/node-minecraft-protocol/pull/759.patch
>>    -
>>    https://github.com/PrismarineJS/node-minecraft-protocol/pull/759.diff
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/PrismarineJS/node-minecraft-protocol/pull/759>, or
>> unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AAR437QQRJO64SRPADXA7YTSDILSZANCNFSM4QPQRI5Q>
>> .
>>
>

2020-08-30 11:53 UTC, rom1504 commented
And update the doc

On Sun, Aug 30, 2020, 13:49 Romain Beaumont <romain.rom1@gmail.com> wrote:

> Still better to do host = undefined to make it explicit it's optional
>
> On Sun, Aug 30, 2020, 13:48 Romain Beaumont <romain.rom1@gmail.com> wrote:
>
>>
>> https://nodejs.org/api/net.html#net_server_listen_port_host_backlog_callback
>> indeed seems like you right, undefined means ipv6+ipv4 on all addresses
>>
>> On Sun, Aug 30, 2020, 13:47 Romain Beaumont <romain.rom1@gmail.com>
>> wrote:
>>
>>>
>>> https://github.com/PrismarineJS/node-minecraft-protocol/blob/8e4978f3793504435d1b8d7235173f2075ce94db/src/server.js#L53
>>> host option goes there fyi
>>>
>>> On Sun, Aug 30, 2020, 13:35 Romain Beaumont <romain.rom1@gmail.com>
>>> wrote:
>>>
>>>> And can you point to the doc saying that undefined means "listen to all
>>>> ipv4 and ipv6 adresses" ? That seems unlikely to me
>>>>
>>>> On Sun, Aug 30, 2020, 11:28 Alexander Ivanov <notifications@github.com>
>>>> wrote:
>>>>
>>>>> ------------------------------
>>>>> You can view, comment on, or merge this pull request online at:
>>>>>
>>>>>   https://github.com/PrismarineJS/node-minecraft-protocol/pull/759
>>>>> Commit Summary
>>>>>
>>>>>    - Add IPv6 support by default
>>>>>
>>>>> File Changes
>>>>>
>>>>>    - *M* src/createServer.js
>>>>>    <https://github.com/PrismarineJS/node-minecraft-protocol/pull/759/files#diff-72d0c3f9716fb76809b19c5c3290d7c2>
>>>>>    (2)
>>>>>
>>>>> Patch Links:
>>>>>
>>>>>    -
>>>>>    https://github.com/PrismarineJS/node-minecraft-protocol/pull/759.patch
>>>>>    -
>>>>>    https://github.com/PrismarineJS/node-minecraft-protocol/pull/759.diff
>>>>>
>>>>> —
>>>>> You are receiving this because you are subscribed to this thread.
>>>>> Reply to this email directly, view it on GitHub
>>>>> <https://github.com/PrismarineJS/node-minecraft-protocol/pull/759>,
>>>>> or unsubscribe
>>>>> <https://github.com/notifications/unsubscribe-auth/AAR437QQRJO64SRPADXA7YTSDILSZANCNFSM4QPQRI5Q>
>>>>> .
>>>>>
>>>>

2020-08-30 11:54 UTC, rom1504 commented
https://nodejs.org/api/net.html#net_server_listen_port_host_backlog_callback
indeed seems like you right, undefined means ipv6+ipv4 on all addresses

On Sun, Aug 30, 2020, 13:47 Romain Beaumont <romain.rom1@gmail.com> wrote:

>
> https://github.com/PrismarineJS/node-minecraft-protocol/blob/8e4978f3793504435d1b8d7235173f2075ce94db/src/server.js#L53
> host option goes there fyi
>
> On Sun, Aug 30, 2020, 13:35 Romain Beaumont <romain.rom1@gmail.com> wrote:
>
>> And can you point to the doc saying that undefined means "listen to all
>> ipv4 and ipv6 adresses" ? That seems unlikely to me
>>
>> On Sun, Aug 30, 2020, 11:28 Alexander Ivanov <notifications@github.com>
>> wrote:
>>
>>> ------------------------------
>>> You can view, comment on, or merge this pull request online at:
>>>
>>>   https://github.com/PrismarineJS/node-minecraft-protocol/pull/759
>>> Commit Summary
>>>
>>>    - Add IPv6 support by default
>>>
>>> File Changes
>>>
>>>    - *M* src/createServer.js
>>>    <https://github.com/PrismarineJS/node-minecraft-protocol/pull/759/files#diff-72d0c3f9716fb76809b19c5c3290d7c2>
>>>    (2)
>>>
>>> Patch Links:
>>>
>>>    -
>>>    https://github.com/PrismarineJS/node-minecraft-protocol/pull/759.patch
>>>    -
>>>    https://github.com/PrismarineJS/node-minecraft-protocol/pull/759.diff
>>>
>>> —
>>> You are receiving this because you are subscribed to this thread.
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/PrismarineJS/node-minecraft-protocol/pull/759>, or
>>> unsubscribe
>>> <https://github.com/notifications/unsubscribe-auth/AAR437QQRJO64SRPADXA7YTSDILSZANCNFSM4QPQRI5Q>
>>> .
>>>
>>

2020-08-30 14:57 UTC, wvffle approved these changes

2020-08-30 14:57 UTC, wvffle commented on src/createServer.js
> +    host,
This looks good to me. I don't see the point of doing `host = undefined`. It is redundant in my opinion.

2020-08-30 15:43 UTC, rom1504 commented
It's not redundant. That marks the parameter as optional.

On Sun, Aug 30, 2020, 16:57 Kasper Seweryn <notifications@github.com> wrote:

> *@wvffle* approved this pull request.
> ------------------------------
>
> In src/createServer.js
> <https://github.com/PrismarineJS/node-minecraft-protocol/pull/759#discussion_r479780077>
> :
>
> > @@ -13,7 +13,7 @@ module.exports = createServer
>
>  function createServer (options = {}) {
>    const {
> -    host = '0.0.0.0',
> +    host,
>
> This looks good to me. I don't see the point of doing host = undefined.
> It is redundant in my opinion.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/PrismarineJS/node-minecraft-protocol/pull/759#pullrequestreview-478210354>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAR437TQRY4MKQA2U3GUM2LSDJSF7ANCNFSM4QPQRI5Q>
> .
>

2020-09-03 05:29 UTC, Saiv46 commented
Where? There are no `.d.ts` files to mark this parameter as optional.

> It's not redundant. That marks the parameter as optional.
> […](#)
> On Sun, Aug 30, 2020, 16:57 Kasper Seweryn ***@***.***> wrote: ***@***.**** approved this pull request. ------------------------------ In src/createServer.js <[#759 (comment)](https://github.com/PrismarineJS/node-minecraft-protocol/pull/759#discussion_r479780077)> : > @@ -13,7 +13,7 @@ module.exports = createServer function createServer (options = {}) { const { - host = '0.0.0.0', + host, This looks good to me. I don't see the point of doing host = undefined. It is redundant in my opinion. — You are receiving this because you commented. Reply to this email directly, view it on GitHub <[#759 (review)](https://github.com/PrismarineJS/node-minecraft-protocol/pull/759#pullrequestreview-478210354)>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAR437TQRY4MKQA2U3GUM2LSDJSF7ANCNFSM4QPQRI5Q> .

2020-09-03 06:55 UTC, rom1504 commented
Just put host = undefined in the function definition

2020-09-03 06:56 UTC, rom1504 commented
And update the doc to explain the new behavior by default for this parameter

2020-09-05 22:11 UTC, rom1504 commented
would be good to finish this

2020-09-18 03:52 UTC, Saiv46 commented
Any progress? `host = undefined` is useless, and `host` parameter just not documented

2020-09-18 07:18 UTC, rom1504 commented
Yes I'm waiting for you to make the changes.
host = undefined is a clear indication for the reader of the code that is parameter is optional.
host parameter is documented in the API.md file

2020-09-18 20:49 UTC, rom1504 commented
I don't really understand what's blocking you here. Seems difficult for you to accept code reviews?
I can do the changes myself, but it seems like a good learning opportunity.

2020-09-27 19:24 UTC, closed without merging