End the serializer instead of unpiping streams
PrismarineJS/node-minecraft-protocol pull request #775
Opened 2020-11-05 18:19 UTC by DeltaEvo

This will let all the streams end their work before
closing the socket

2020-11-06 03:56 UTC, wvffle requested changes

2020-11-06 03:56 UTC, wvffle commented on src/client.js
> +    if (this.serializer) this.serializer.end()
Use brackets here

2020-11-11 11:54 UTC, DeltaEvo commented
gentle ping @wvffle

2020-11-11 12:18 UTC, rom1504 commented
With this change, the socket would never be closed from node-minecraft-protocol side (both as a server and as a client).
The other party might not close the connection.
This is a breaking change as called of client.end expect the connection to be closed now.
Introducing a new method for this use case might be better.
What do you think ?

2020-11-11 17:12 UTC, DeltaEvo commented
> With this change, the socket would never be closed from node-minecraft-protocol side (both as a server and as a client).

No the socket will be still closed but not right away https://nodejs.org/api/stream.html#stream_readable_pipe_destination_options pipe have an `end` option that is by default to true to according to the doc `End the writer when the reader ends. Default: true.`
In practice this means that the writer will be ended when the reader will be finished
I added a comment that explain this `ending the serializer will end the whole chain: serializer -> framer -> socket -> splitter -> deserializer`

ending the serializer will cause the socket to end but not right away it will let the serializer and the framer finish what it was doing before

When we ended the socket and unpiped the stream if the serializer still had packet to serialize they were lost since no one was consuming the stream

And if the socket takes times to end there is still the closeTimeout that will destroy the socket and so force the close if it

2020-11-11 17:15 UTC, DeltaEvo commented
And about the code inside end I kept the check for the socket `if (this.socket)` but is there a case in this code where the socket is not defined ? same for the serializer ?

2020-11-11 17:24 UTC, rom1504 commented
> pipe have an end option that is by default to true to according to the doc End the writer when the reader ends. Default: true.
the serializer is a writer, the socket is a reader
so the writer is ending, that doesn't make the reader end

2020-11-11 17:29 UTC, DeltaEvo commented
> the serializer is a writer, the socket is a reader

It's a Duplex stream so it's Readable and Writable and the Readable part is piped inside the Writable part of the framer. The framer is also a Duplex Stream and the Readable part of it is piped into the Writable part of the socket

2020-12-05 15:51 UTC, rom1504 approved these changes

2020-12-05 15:51 UTC, merged