Fix incorrect protocol message
PrismarineJS/node-minecraft-protocol pull request #777
Opened 2020-11-10 20:44 UTC by Heath123

I didn't really make this, so I set it as co-authored
Sets the state to login before sending the message so it gets interpreted properly by the client

2020-11-10 20:57 UTC, DeltaEvo requested changes

2020-11-10 20:57 UTC, DeltaEvo commented on src/server/handshake.js
> +
You need to assign `client.version` before `client.state` since `version` is used to build the serializer

2020-11-10 21:05 UTC, DeltaEvo commented on src/server/handshake.js
> +
Or reassign client.state to rebuild the serializer :thinking:

What do you think @rom1504 ?

2020-12-05 15:53 UTC, rom1504 commented
Does this really work? It seems to me it won't work due to lot of things being done when the state is changed

2020-12-05 16:41 UTC, Heath123 commented
> Does this really work? It seems to me it won't work due to lot of things being done when the state is changed

I need to update it but I haven't gotten around to it yet

2021-03-14 22:51 UTC, rom1504 commented
stale, reopen if you want to do it

2021-03-14 22:51 UTC, closed without merging