Make mc.ping return a promise instead of using callbacks
PrismarineJS/node-minecraft-protocol pull request #849
Opened 2021-04-17 12:53 UTC by AngeryFrog

It's not a suggestion I've seen however having mc.ping return a promise instead of using a callback will allow for people too use async await on this making for cleaner code.

2021-04-17 14:21 UTC, u9g commented
lint

2021-04-17 15:24 UTC, rom1504 commented
Can you make it both take a callback and return a promise like in https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/book.js#L86 to avoid making it a breaking change ?

2021-04-17 15:32 UTC, u9g commented
if you just wrapped this in a promise and thats it, why cant we wrap this and do `mc.ping = callbackify(promisify(mc.ping))`

2021-04-17 18:28 UTC, AngeryFrog commented
Sure give me a few mins

2021-04-17 18:40 UTC, AngeryFrog commented
Updated the ping function too both return a promise use a callback function if present

2021-05-01 23:15 UTC, rom1504 commented
tests failing

2021-05-02 18:48 UTC, AngeryFrog commented
after testing on local machine produces 2 errors
```
1) client 1.7.10
       offline
         produce a decent error when connecting with the wrong version:
     Error: read ECONNRESET
      at TCP.onStreamRead (internal/stream_base_commons.js:209:20)

  2) client 1.8.8
       offline
         produce a decent error when connecting with the wrong version:
     Error: read ECONNRESET
      at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
```
 however unsure too the cause, is anyone else able too replicate and/or give a suggestion too the cause?

2021-06-16 20:47 UTC, rom1504 requested changes
could you use promise and just use a callbackify function to re-add the callback ?
otherwise it makes the code too complex

2021-06-17 18:18 UTC, AngeryFrog commented
I hope this is what was intended, if not please comment and I'll re-review it

2021-06-19 20:03 UTC, rom1504 approved these changes

2021-06-19 20:03 UTC, merged