Add a way to encode a packet only once and send it to multiple clients
PrismarineJS/node-minecraft-protocol pull request #851
Opened 2021-04-20 16:16 UTC by GroobleDierne

Close #713

I assumed this will only be used with clients in "play" state.

2021-04-20 16:30 UTC, u9g approved these changes
lgtm

2021-04-20 16:35 UTC, Karang approved these changes
LGTM

2021-04-20 20:39 UTC, rom1504 commented
Could you add a test (in server.js in test folder) ?
For example send chat to 2 clients and make sure they receive it.
This is a pretty fundamental feature so I think it deserves testing

2021-04-20 21:04 UTC, GroobleDierne commented
Yes I'll do it when I have the time

2021-04-22 17:22 UTC, GroobleDierne commented
Ready 👍

2021-04-23 14:22 UTC, rom1504 requested changes

2021-04-23 14:22 UTC, rom1504 commented on test/serverTest.js
> +        server.writeToClients(Object.values(server.clients), 'chat', { message: JSON.stringify({ text: 'A message from the server.' }), position: 1, sender: '00000000-0000-0000-0000-000000000000' })
you need to wait for client to receive the chat message

2021-04-24 17:13 UTC, GroobleDierne commented
Done

2021-05-01 23:12 UTC, merged